### ISSUE TITLE
AssertionError: Datasets/Stanford_Dogs/train.json dir not found

### ISSUE THREAD

**Issue by JiuqingDong** [KMnP/vpt#43]
I run this command and got an Error:
# Tune CUB with VPT:
python tune_fgvc.py \
    --train-type "prompt" \
    --config-file configs/prompt/dogs.yaml \
    MODEL.TYPE "vit" \
    DATA.BATCH_SIZE "16" \
    MODEL.PROMPT.DEEP "True" \
    MODEL.PROMPT.DROPOUT "0.1" \
    MODEL.PROMPT.NUM_TOKENS "10" \
    DATA.FEATURE "sup_vitb16_imagenet21k" \
    DATA.DATAPATH "Datasets/Stanford_Dogs" \
    MODEL.MODEL_ROOT "models/" \
    OUTPUT_DIR "./output/"

[06/22 15:18:50 visual_prompt]: Loading training data (final training data for vtab)...
[06/22 15:18:50 visual_prompt]: Constructing StanfordDogs dataset train...
anno_path Datasets/Stanford_Dogs/train.json
Traceback (most recent call last):
  File "tune_fgvc.py", line 208, in <module>
    main(args)
  File "tune_fgvc.py", line 199, in main
    prompt_main(args)
  File "tune_fgvc.py", line 165, in prompt_main
    train_main(cfg, args)
  File "/home/multiai3/Jiuqing/VPT/train.py", line 102, in train
    train_loader, val_loader, test_loader = get_loaders(cfg, logger)
  File "/home/multiai3/Jiuqing/VPT/train.py", line 71, in get_loaders
    train_loader = data_loader.construct_train_loader(cfg)
  File "/home/multiai3/Jiuqing/VPT/src/data/loader.py", line 64, in construct_train_loader
    drop_last=drop_last,
  File "/home/multiai3/Jiuqing/VPT/src/data/loader.py", line 36, in _construct_loader
    dataset = _DATASET_CATALOG[dataset_name](cfg, split)
  File "/home/multiai3/Jiuqing/VPT/src/data/datasets/json_dataset.py", line 151, in __init__
    super(DogsDataset, self).__init__(cfg, split)
  File "/home/multiai3/Jiuqing/VPT/src/data/datasets/json_dataset.py", line 34, in __init__
    self._construct_imdb(cfg)
  File "/home/multiai3/Jiuqing/VPT/src/data/datasets/json_dataset.py", line 59, in _construct_imdb
    anno = self.get_anno()
  File "/home/multiai3/Jiuqing/VPT/src/data/datasets/json_dataset.py", line 46, in get_anno
    assert os.path.exists(anno_path), "{} dir not found".format(anno_path)
AssertionError: Datasets/Stanford_Dogs/train.json dir not found

I search for this Error in Issues but no result. If you are available, could you tell me why I get this Error?

**Comment by Jasper0420** [comment]
May I ask if you solved it? How did you solve it? Thank you.

**Comment by lmg1999** [comment]
I get the same error,could you tell me why I get this Error?

**Comment by JiuqingDong** [comment]
> I get the same error,could you tell me why I get this Error?

I forgot about this, but I guess you can generate a JSON file like this:
<img width="390" alt="image" src="https://github.com/KMnP/vpt/assets/111500217/c8a12597-f4e5-40ae-9f09-6450ed43ff31">
The example is Food101 dataset.

**Comment by ACupofAir** [comment]
> > I get the same error,could you tell me why I get this Error?
> 
> I forgot about this, but I guess you can generate a JSON file like this: <img alt="image" width="390" src="https://private-user-images.githubusercontent.com/111500217/301481829-c8a12597-f4e5-40ae-9f09-6450ed43ff31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTE1MjUsIm5iZiI6MTcxOTk5MTIyNSwicGF0aCI6Ii8xMTE1MDAyMTcvMzAxNDgxODI5LWM4YTEyNTk3LWY0ZTUtNDBhZS05ZjA5LTY0NTBlZDQzZmYzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNzIwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTg4Njk0NWYyNjYxMWFhOTc3MzE1ODUwOTIwZjhhZjhhNDkyODg0NDE0NmEwMjdkMTYwMDcxYWM0MTA5NjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FP5-6UOBi4NdzH5-N74ZLFow6E-jJlW6ycKWvMl1-64"> The example is Food101 dataset.

Could you provide the train.json you generated, for you have done this experiment, ready-made json files can save my time and errors. Thanks.
